[package]
name = "npc-engine-utils"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
npc-engine-common = { path = "../npc-engine-common", features = ["graphviz"] }
log = "0.4"
ansi_term = "0.12"
rand = "0.8"